---
abstract: Routes
author:
  - 'Viacheslav Tykhanovskyi <vti@cpan.org>'
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Routes-Tiny
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Carp: 0
  perl: 5.008007
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/vti/routes-tiny
version: 0.009014
